### ISSUE TITLE
【要望】bizevoと違うページに移動するときは別タブが嬉しい

### ISSUE THREAD

**Issue by morohashiyuu** [wata-gh/bizevo#111]
画面上部のメニューがなくなる画面に遷移するときは別タブが嬉しいです。（戻りづらいので）

GitHubのページだけかも。
Kiitaは逆に上部にメニューがあると嬉しい。

**Comment by wata-gh** [comment]
要望どうもです。
別タブで開きたい人の方が少ないと考えていますので、デフォルトはままで、開きたい人がCtrlを押しながらでお願いしたいです。
他の人も同じ意見が多いなら検討します。

**Comment by morohashiyuu** [comment]
なるほど。その発想がなかったです。了解です
